// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnU1ZOBnmSCDTZPefabYv9yMin80TAWG4',
    appId: '1:236989254194:web:9c88ec7d27db9ff1960a2b',
    messagingSenderId: '236989254194',
    projectId: 'epl-3-the-brief',
    authDomain: 'epl-3-the-brief.firebaseapp.com',
    storageBucket: 'epl-3-the-brief.firebasestorage.app',
    measurementId: 'G-SQ362E87SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIG2b6x7VLBVbveoWQCDOFbrduh40WCY0',
    appId: '1:236989254194:android:e9b9a1f2f9015602960a2b',
    messagingSenderId: '236989254194',
    projectId: 'epl-3-the-brief',
    storageBucket: 'epl-3-the-brief.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYEI5MKj35ZyJus-4fy8ULWkofxKnnzaw',
    appId: '1:236989254194:ios:10cc1b37db569729960a2b',
    messagingSenderId: '236989254194',
    projectId: 'epl-3-the-brief',
    storageBucket: 'epl-3-the-brief.firebasestorage.app',
    iosClientId: '236989254194-613no9hrg6hlhifbfbbtrjet3r50gkev.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilotWeatherBriefing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYEI5MKj35ZyJus-4fy8ULWkofxKnnzaw',
    appId: '1:236989254194:ios:10cc1b37db569729960a2b',
    messagingSenderId: '236989254194',
    projectId: 'epl-3-the-brief',
    storageBucket: 'epl-3-the-brief.firebasestorage.app',
    iosClientId: '236989254194-613no9hrg6hlhifbfbbtrjet3r50gkev.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilotWeatherBriefing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnU1ZOBnmSCDTZPefabYv9yMin80TAWG4',
    appId: '1:236989254194:web:f79fb1d000a2b89c960a2b',
    messagingSenderId: '236989254194',
    projectId: 'epl-3-the-brief',
    authDomain: 'epl-3-the-brief.firebaseapp.com',
    storageBucket: 'epl-3-the-brief.firebasestorage.app',
    measurementId: 'G-QHTYEWJJRX',
  );

}